### ISSUE TITLE
Include port in Url.base

### ISSUE THREAD

**Issue by frennkie** [python-ln/lnurl#5]
https://github.com/python-ln/lnurl/blob/6a6cedf29e24ff0c532735b37ec3e09cca9d2e9c/lnurl/types.py#L81

Is the **port** omitted intentionally? As far as I understand all of the following are valid URL, right?!

* http://foobarxxx...xxxx.onion/foo
* http://foobarxxx...xxxx.onion:80/foo
* https://foobarxxxx...xxx.onion/foo
* https://foobarxxxx...xxx.onion:443/foo
* https://foobarxxxx...xxx.onion:8443/foo
* https://foo.example.com/foo
* https://foo.example.com:443/foo
* https://foo.example.com:8443/foo

Should the **base** not always contain the port?

**Comment by jogc** [comment]
@eillarra ?

**Comment by eillarra** [comment]
Fixed on 1e803287766f004705abe6ba340ca96473f114af
